spring:
  datasource:
    password: 2005
    username: postgres
    url: jdbc:postgresql://localhost:5432/meal
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

api:
  info:
    title: Pdp Meal API
    description: This is the meal service api for PDP staff
    version: 1.0
    terms-of-service: https://unicorn.pdp.uz
    contact-name: pdp.uz
    contact-email: john.lgd65@gmail.com
    contact-url: https://pdp.uz
    license-name: Apache 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0.html

service:
  prop:
    protocol: http
    ip: localhost
    port: 8080
    url: boom.uz

springdoc:
  swagger-ui:
    path: swagger-ui
  api-docs:
    path: /api-docs

telegram:
  bot:
    token: 5111889146:AAHRS4doUEZAfHnDd9HIdU_1bqko9cy-Jxg
    username: '@pdp_lunch_bot'